`include "define.svh"
`include "uvm_macros.svh"
import uvm_pkg::*;

module SPI_Master_v1_0_S00_AXI #(
    // Users to add parameters here

    // User parameters ends
    // Do not modify the parameters beyond this line

    // Width of S_AXI data bus
    parameter integer C_S_AXI_DATA_WIDTH = 32,
    // Width of S_AXI address bus
    parameter integer C_S_AXI_ADDR_WIDTH = 4
) (
    // Users to add ports here
    // [수정됨] 32비트 통짜 레지스터를 제거하고, 명확한 I/O 포트로 대체
    output wire       cpol,
    output wire       cpha,
    output wire [7:0] clk_div,
    output wire [7:0] tx_data,
    output wire       start,
    input  wire [7:0] rx_data,
    input  wire       done,
    input  wire       busy,
    // User ports ends
    // Do not modify the ports beyond this line

    // Global Clock Signal
    input  wire                                  S_AXI_ACLK,
    input  wire                                  S_AXI_ARESETN,
    input  wire [    C_S_AXI_ADDR_WIDTH-1 : 0] S_AXI_AWADDR,
    input  wire [                         2 : 0] S_AXI_AWPROT,
    input  wire                                  S_AXI_AWVALID,
    output wire                                  S_AXI_AWREADY,
    input  wire [    C_S_AXI_DATA_WIDTH-1 : 0] S_AXI_WDATA,
    input  wire [(C_S_AXI_DATA_WIDTH/8)-1 : 0] S_AXI_WSTRB,
    input  wire                                  S_AXI_WVALID,
    output wire                                  S_AXI_WREADY,
    output wire [                         1 : 0] S_AXI_BRESP,
    output wire                                  S_AXI_BVALID,
    input  wire                                  S_AXI_BREADY,
    input  wire [    C_S_AXI_ADDR_WIDTH-1 : 0] S_AXI_ARADDR,
    input  wire [                         2 : 0] S_AXI_ARPROT,
    input  wire                                  S_AXI_ARVALID,
    output wire                                  S_AXI_ARREADY,
    output wire [    C_S_AXI_DATA_WIDTH-1 : 0] S_AXI_RDATA,
    output wire [                         1 : 0] S_AXI_RRESP,
    output wire                                  S_AXI_RVALID,
    input  wire                                  S_AXI_RREADY
);

    // AXI4LITE signals
    reg [C_S_AXI_ADDR_WIDTH-1 : 0] axi_awaddr;
    reg                            axi_awready;
    reg                            axi_wready;
    reg [                   1 : 0] axi_bresp;
    reg                            axi_bvalid;
    reg [C_S_AXI_ADDR_WIDTH-1 : 0] axi_araddr;
    reg                            axi_arready;
    reg [C_S_AXI_DATA_WIDTH-1 : 0] axi_rdata;
    reg [                   1 : 0] axi_rresp;
    reg                            axi_rvalid;

    localparam integer ADDR_LSB = (C_S_AXI_DATA_WIDTH / 32) + 1;
    localparam integer OPT_MEM_ADDR_BITS = 1;

    // Number of Slave Registers 4
    reg     [C_S_AXI_DATA_WIDTH-1:0] slv_reg0;
    reg     [C_S_AXI_DATA_WIDTH-1:0] slv_reg1;
    // [수정됨] slv_reg2는 입력 신호(rx_data, done, busy)를 직접 조립해서 읽으므로 reg 선언이 불필요합니다.
    // reg     [C_S_AXI_DATA_WIDTH-1:0] slv_reg2; 
    reg     [C_S_AXI_DATA_WIDTH-1:0] slv_reg3;
    wire                             slv_reg_rden;
    wire                             slv_reg_wren;
    reg     [C_S_AXI_DATA_WIDTH-1:0] reg_data_out;
    integer                          byte_index;
    reg                              aw_en;

    // I/O Connections assignments
    assign S_AXI_AWREADY = axi_awready;
    assign S_AXI_WREADY  = axi_wready;
    assign S_AXI_BRESP   = axi_bresp;
    assign S_AXI_BVALID  = axi_bvalid;
    assign S_AXI_ARREADY = axi_arready;
    assign S_AXI_RDATA   = axi_rdata;
    assign S_AXI_RRESP   = axi_rresp;
    assign S_AXI_RVALID  = axi_rvalid;



	//$monitor("[%0t] awready=%0b, wready=%0b, bvalid=%0b, arready=%0b, rvalid=%0b", $time, v_if.awready, v_if.wready, v_if.bvalid, v_if.arready, v_if.rvalid);

    // Implement axi_awready generation
    always @(posedge S_AXI_ACLK) begin
        if (S_AXI_ARESETN == 1'b0) begin
            axi_awready <= 1'b0;
            aw_en <= 1'b1;
        end else begin
            if (~axi_awready && S_AXI_AWVALID && S_AXI_WVALID && aw_en) begin
                axi_awready <= 1'b1;
                aw_en <= 1'b0;
				`uvm_info("axi_awready_gen", "awready 1", UVM_DEBUG)
            end else if (S_AXI_BREADY && axi_bvalid) begin
                aw_en <= 1'b1;
                axi_awready <= 1'b0;
            end else begin
                axi_awready <= 1'b0;
            end
        end
    end

    // Implement axi_awaddr latching
    always @(posedge S_AXI_ACLK) begin
        if (S_AXI_ARESETN == 1'b0) begin
            axi_awaddr <= 0;
        end else begin
            if (~axi_awready && S_AXI_AWVALID && S_AXI_WVALID && aw_en) begin
                axi_awaddr <= S_AXI_AWADDR;
            end
        end
    end

    // Implement axi_wready generation
    always @(posedge S_AXI_ACLK) begin
        if (S_AXI_ARESETN == 1'b0) begin
            axi_wready <= 1'b0;
        end else begin
            if (~axi_wready && S_AXI_WVALID && S_AXI_AWVALID && aw_en) begin
                axi_wready <= 1'b1;
				`uvm_info("axi_wready_gen", "wready 1", UVM_DEBUG)
            end else begin
                axi_wready <= 1'b0;
            end
        end
    end

    // Implement memory mapped register select and write logic generation
    assign slv_reg_wren = axi_wready && S_AXI_WVALID && axi_awready && S_AXI_AWVALID;

    always @(posedge S_AXI_ACLK) begin
        if (S_AXI_ARESETN == 1'b0) begin
            slv_reg0 <= 0;
            slv_reg1 <= 0;
            slv_reg3 <= 0;
        end else begin
            if (slv_reg_wren) begin
                case (axi_awaddr[ADDR_LSB+OPT_MEM_ADDR_BITS:ADDR_LSB])
                    2'h0:
                    for ( byte_index = 0; byte_index <= (C_S_AXI_DATA_WIDTH / 8) - 1; byte_index = byte_index + 1 )
                        if (S_AXI_WSTRB[byte_index] == 1) begin
                            slv_reg0[(byte_index*8) +: 8] <= S_AXI_WDATA[(byte_index*8) +: 8];
                        end
                    2'h1:
                    for ( byte_index = 0; byte_index <= (C_S_AXI_DATA_WIDTH / 8) - 1; byte_index = byte_index + 1 )
                        if (S_AXI_WSTRB[byte_index] == 1) begin
                            slv_reg1[(byte_index*8) +: 8] <= S_AXI_WDATA[(byte_index*8) +: 8];
                        end
                    // 2'h2는 읽기 전용(Status RX)이므로 쓰기 로직에서 제거함
                    2'h3:
                    for ( byte_index = 0; byte_index <= (C_S_AXI_DATA_WIDTH / 8) - 1; byte_index = byte_index + 1 )
                        if (S_AXI_WSTRB[byte_index] == 1) begin
                            slv_reg3[(byte_index*8) +: 8] <= S_AXI_WDATA[(byte_index*8) +: 8];
                        end
                    default: begin
                        slv_reg0 <= slv_reg0;
                        slv_reg1 <= slv_reg1;
                        slv_reg3 <= slv_reg3;
                    end
                endcase

				`uvm_info("[AXI_REG]", $sformatf("%saxi_awaddr=0x%0h, [3:2]=0x%0h, AXI_WDATA=0x%0h\nreg0:%0h, reg1:%0h, reg2:%0h, reg3:%0h%s", `CLR_GRN, axi_awaddr, axi_awaddr[3:2], S_AXI_WDATA, slv_reg0, slv_reg1, {22'd0, busy,done,rx_data}, slv_reg3, `CLR_RESET), UVM_DEBUG)
            end
        end
    end

    // Implement write response logic generation
    always @(posedge S_AXI_ACLK) begin
        if (S_AXI_ARESETN == 1'b0) begin
            axi_bvalid <= 0;
            axi_bresp  <= 2'b0;
        end else begin
            if (axi_awready && S_AXI_AWVALID && ~axi_bvalid && axi_wready && S_AXI_WVALID) begin
                axi_bvalid <= 1'b1;
                axi_bresp  <= 2'b0; 
				`uvm_info("axi_bvalid_gen", "bvalid 1", UVM_DEBUG)
            end else begin
                if (S_AXI_BREADY && axi_bvalid) begin
                    axi_bvalid <= 1'b0;
                end
            end
        end
    end

    // Implement axi_arready generation
    always @(posedge S_AXI_ACLK) begin
        if (S_AXI_ARESETN == 1'b0) begin
            axi_arready <= 1'b0;
            axi_araddr  <= 32'b0;
        end else begin
            if (~axi_arready && S_AXI_ARVALID) begin
                axi_arready <= 1'b1;
                axi_araddr  <= S_AXI_ARADDR;
				`uvm_info("axi_arready_gen", "arready 1", UVM_DEBUG)
            end else begin
                axi_arready <= 1'b0;
            end
        end
    end

    // Implement axi_arvalid generation
    always @(posedge S_AXI_ACLK) begin
        if (S_AXI_ARESETN == 1'b0) begin
            axi_rvalid <= 0;
            axi_rresp  <= 0;
        end else begin
            if (axi_arready && S_AXI_ARVALID && ~axi_rvalid) begin
                axi_rvalid <= 1'b1;
				`uvm_info("axi_rvalid_gen", "rvalid 1", UVM_DEBUG)
                axi_rresp  <= 2'b0; 
            end else if (axi_rvalid && S_AXI_RREADY) begin
                axi_rvalid <= 1'b0;
            end
        end
    end

    // Implement memory mapped register select and read logic generation
    assign slv_reg_rden = axi_arready & S_AXI_ARVALID & ~axi_rvalid;
    always @(*) begin
        case (axi_araddr[ADDR_LSB+OPT_MEM_ADDR_BITS:ADDR_LSB])
            2'h0    : reg_data_out <= slv_reg0;
            2'h1    : reg_data_out <= slv_reg1;
            // [수정됨] 읽기 요청이 오면(offset 0x08), 입력받은 개별 신호들을 즉석에서 32비트로 조립하여 넘겨줌
            2'h2    : reg_data_out <= {22'd0, busy, done, rx_data}; 
            2'h3    : reg_data_out <= slv_reg3;
            default : reg_data_out <= 0;
        endcase
		//		`uvm_info("[AXI_REG]", $sformatf("%sreg0:%0h, reg1:%0h, reg2:%0h, reg3:%0h%s", `CLR_GRN, slv_reg0, slv_reg1, {22'd0, busy,done,rx_data}, slv_reg3, `CLR_RESET), UVM_DEBUG)
    end

    // Output register or memory read data
    always @(posedge S_AXI_ACLK) begin
        if (S_AXI_ARESETN == 1'b0) begin
            axi_rdata <= 0;
        end else begin
            if (slv_reg_rden) begin
                axi_rdata <= reg_data_out; 
            end
        end
    end

    // =========================================================================
    // [수정됨] Add user logic here: AXI 쓰기 레지스터 값을 외부 포트로 출력 매핑
    // =========================================================================
    assign cpol    = slv_reg0[0];        // 0번 비트
    assign cpha    = slv_reg0[1];        // 1번 비트
    assign clk_div = slv_reg0[15:8];     // 8~15번 비트

    assign tx_data = slv_reg1[7:0];      // 0~7번 비트
    assign start   = slv_reg1[31];       // 31번 비트
    // User logic ends

endmodule
